# Generated by Django 4.0.5 on 2023-08-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
