# Generated by Django 4.0.5 on 2023-08-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_enquiry', '0002_enquirydatabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirydatabase',
            name='Age',
        ),
        migrations.AddField(
            model_name='enquirydatabase',
            name='Query',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
